Traceback (most recent call last):
  File "C:\Users\backg\AppData\Roaming\Python\Python37\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\backg\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\backg\AppData\Roaming\Python\Python37\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\backg\AppData\Roaming\Python\Python37\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "c:\program files\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\backg\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\backg\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\backg\AppData\Roaming\Python\Python37\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
subs1 = {mu - 3*x**2: mu}

J1 = J.subs(subs1)

J1.eigenvects()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_13624/473298485.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0msubs1[0m [1;33m=[0m [1;33m{[0m[0mmu[0m [1;33m-[0m [1;36m3[0m[1;33m*[0m[0mx[0m[1;33m**[0m[1;36m2[0m[1;33m:[0m [0mmu[0m[1;33m}[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m [0mJ1[0m [1;33m=[0m [0mJ[0m[1;33m.[0m[0msubs[0m[1;33m([0m[0msubs1[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;33m[0m[0m
[0;32m      5[0m [0mJ1[0m[1;33m.[0m[0meigenvects[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mTypeError[0m: unhashable type: 'numpy.ndarray'
TypeError: unhashable type: 'numpy.ndarray'

